export const formStyles = {
  pageBackground: {
    position: "fixed",
    inset: 0,
    minHeight: "100dvh",
    width: "100vw",
    m: 0,
    p: 0,
    overflow: "hidden",
    backgroundImage: "url('/images/login-bg.png')",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    display: "flex",
    justifyContent: "right",
    alignItems: "center",
  },
  container: {
    maxWidth: { xs: 320, sm: 400 },
    mx: "auto",
    mt: 8,
    px: 3,
    py: 4,
    background: "rgba(164, 198, 236, 0.25)",
    borderRadius: "16px",
    boxShadow: "0 4px 30px rgba(0, 0, 0, 0.1)",
    backdropFilter: "blur(13.5px)",
    WebkitBackdropFilter: "blur(13.5px)",
    border: "1px solid rgba(164, 198, 236, 0.42)",
    transition: "all 0.3s ease",
    "&:hover": { boxShadow: 5 },
  },
  title: {
    textAlign: "center",
    fontWeight: "bold",
    color: "text.primary",
  },
  submitButton: {
    mt: 2,
    py: 1.5,
    fontSize: "1rem",
    borderRadius: 2,
    textTransform: "none",
    fontWeight: "bold",
    boxShadow: "none",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "primary.dark",
    },
  },
  linkText: {
    fontSize: "0.9rem",
    color: "text.secondary",
    textAlign: "center",
    mt: 1,
  },
  link: {
    fontWeight: "bold",
    textDecoration: "none",
    "&:hover": { textDecoration: "underline" },
  },
};
